name: CI

on:
  # push:
  #   branches: [ main, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter 3.41.7
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Format
        run: dart format --output=none --set-exit-if-changed .

      - name: Static Analysis
        run: flutter analyze .

      - name: Run Tests
        # Si no hay directorio 'test', ignorará el error
        run: if [ -d "test" ]; then flutter test; else echo "No tests to run"; fi
